PortfolioDetailsFragment
ArtemShendelyar/MyAssets pull request #10
Opened 2024-08-11 15:48 UTC by belgoscode

# Изменения:
- Слегка переработана структура интерактора портфелей и взаимосвязанных классов: `getPortfolioById` заменен на `getPortfolioByListPosition` для избежания ошибок при адресации из ресайклера.
- Создан фрагмент `PortfolioDetailsFragment`, на данный момент имеющий в себе функциональность изменения имени портфеля и его удаления с подтверждением.

[Демонстрация](https://github.com/user-attachments/assets/d91e4ef5-6515-4d10-92df-043a7efd3197)

2024-08-11 17:20 UTC, ArtemShendelyar approved these changes
Глянул у себя. Запускается. Вёрстка не плывёт.

2024-08-12 12:44 UTC, Valentin2508247 requested changes
использование position в списке как id для portfolio некорректно
верни использование portfolio.id

2024-08-12 12:44 UTC, Valentin2508247 commented on app/src/main/java/domain/entity/PortfolioItem.kt
>  data class PortfolioItem(
оставь val, мутабельность зло

2024-08-12 12:44 UTC, Valentin2508247 commented on app/src/main/java/domain/entity/Portfolio.kt
> +    var name: String
оставь val, мутабельность зло

2024-08-12 12:44 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioListFragment.kt
> +                        itemId
в твой реализации сюда передается позиция айтема в recyclerView, а не itemId

2024-08-12 12:44 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioDetailsViewModel.kt
> +            renamedPortfolio.name = newName
renamedPortfolio.copy(name = newName) вместо мутабельных полей

2024-08-12 12:44 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioDetailsViewModel.kt
> +            val renamedPortfolioResult = portfolioInteractor.getPortfolioByListPosition(portfolioId)
вынеси логику в отдельный метод интерактора

2024-08-12 12:44 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioDetailsViewModel.kt
сделай обработку ошибок

2024-08-12 12:44 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioDetailsFragment.kt
> +                findNavController().navigateUp()
плохо делать findNavController().navigateUp() в случае null
у LiveData default значение null и есть шанс, что запрос к данным не успеет выполнится
при смене data source твой код скорее всего перестанет работать

2024-08-12 12:58 UTC, belgoscode commented on app/src/main/java/domain/entity/Portfolio.kt
> +    var name: String
Как в таком случае реализовать переименование портфолио?

2024-08-13 07:43 UTC, Valentin2508247 commented on app/src/main/java/domain/entity/Portfolio.kt
> +    var name: String
portfolio.copy(name = "New name")

2024-08-14 07:46 UTC, Valentin2508247 requested changes

2024-08-14 07:46 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioDetailsViewModel.kt
> +                val portfolioResult = portfolioInteractor.getPortfolioById(id)
используй onSuccess и onFailure у Result<T>

2024-08-14 13:27 UTC, Valentin2508247 approved these changes

2024-08-15 11:06 UTC, merged