DataBase
ArtemShendelyar/MyAssets pull request #11
Opened 2024-08-15 12:37 UTC by ArtemShendelyar

Рабочая версия. Но не лучшая.

2024-08-16 12:59 UTC, belgoscode approved these changes

2024-08-16 13:31 UTC, Valentin2508247 requested changes

2024-08-16 13:31 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioListFragment.kt
> +        viewModel.fetchPortfolioList()
почему обращение к данным в onResume?

2024-08-16 13:31 UTC, Valentin2508247 commented on app/src/main/java/data/local/db/entity/PortfolioDb.kt
> +    @PrimaryKey
есть опция использовать autogenerate id

2024-08-16 13:31 UTC, Valentin2508247 commented on app/src/main/java/data/PortfolioDbDataSource.kt
> +        val portfolioDb = PortfolioDb(portfolioDao.getSize() + 1, "New portfolio")
некрасиво и не очень эффективно так генерировать id
используй autogenerate id

2024-08-16 13:31 UTC, Valentin2508247 commented on app/src/main/java/data/PortfolioDbDataSource.kt
> +        val portfolioDb = PortfolioDb(portfolioDao.getSize() + 1, "New portfolio")
захардкоженное "New portfolio" тоже не очень

2024-08-16 13:31 UTC, Valentin2508247 commented on app/src/main/java/data/local/db/entity/AssetsDb.kt
с autogenerate id будет легче работать

2024-08-16 17:58 UTC, pzinkevich42innowise requested changes

2024-08-16 17:58 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioListViewModel.kt
> +            fetchPortfolioList()
Можно подписаться на изменения базы на этом экране, чтобы не городить такое

2024-08-16 17:58 UTC, pzinkevich42innowise commented on app/src/main/java/data/PortfolioDbDataSource.kt
> +    override suspend fun createAndInitPortfolio(portfolio: Portfolio) {
Плохой нейминг метода. В чём заключается инит?

2024-08-16 17:58 UTC, pzinkevich42innowise commented on app/src/main/java/data/PortfolioDbDataSource.kt
> +    override suspend fun updatePortfolio(id: Int, portfolio: Portfolio) {
Почему бы не сделать один Upsert метод с названием save?

2024-08-16 17:58 UTC, pzinkevich42innowise commented on app/src/main/java/data/local/LocalDatabase.kt
> +        PortfolioDb::class
У тебя в этом ПРе как-то побольше сущностей

2024-08-16 17:58 UTC, pzinkevich42innowise commented on app/src/main/java/data/local/db/dao/PortfolioDao.kt
> +    fun getSize(): Int
Зачем?

2024-08-16 17:58 UTC, pzinkevich42innowise commented on app/src/main/java/data/local/db/entity/AssetsDb.kt
> +open class AssetsDb(
Зачем этот класс нужен?

2024-08-19 03:34 UTC, ArtemShendelyar commented on app/src/main/java/data/local/db/entity/AssetsDb.kt
> +open class AssetsDb(
Позже добавим.

2024-08-19 03:35 UTC, ArtemShendelyar commented on app/src/main/java/data/PortfolioDbDataSource.kt
> +    override suspend fun createAndInitPortfolio(portfolio: Portfolio) {
Создания портфеля с заранее известными параметрами. Иначе было бы createPortfolio().

2024-08-19 03:35 UTC, ArtemShendelyar commented on app/src/main/java/data/PortfolioDbDataSource.kt
> +    override suspend fun createAndInitPortfolio(portfolio: Portfolio) {
Функция не моя( К слову).

2024-08-19 04:16 UTC, ArtemShendelyar commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioListFragment.kt
> +        viewModel.fetchPortfolioList()
Потому что не обновляется UI при переходе на этот экран с деталей.

2024-08-19 04:59 UTC, ArtemShendelyar commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioListViewModel.kt
> +            fetchPortfolioList()
Не уверен что знаю как правильно. Стоит изменять репозиторий и возвращать тогда Flow либо LiveData? Но в репозитории же обычно не желательно использовать библиотеки. Domain слой жеж.

2024-08-19 13:53 UTC, Valentin2508247 requested changes

2024-08-19 13:53 UTC, Valentin2508247 commented on app/src/main/java/data/local/db/entity/PortfolioDb.kt
>      val id: Int,
val id: Int = 0

2024-08-19 13:53 UTC, Valentin2508247 commented on app/src/main/java/data/PortfolioDbDataSource.kt
> +        val portfolioDb = PortfolioDb(Random.nextInt(), name = "New portfolio")
мне кажется, или тут есть случайный риск затереть элемент
не генерируй id для записей в бд

2024-08-22 08:11 UTC, ArtemShendelyar commented on app/src/main/java/data/PortfolioDbDataSource.kt
> +        val portfolioDb = PortfolioDb(Random.nextInt(), name = "New portfolio")
Очень поздно увидел, что если ставить значение в 0 для INT полей, то оно будет генерировать id уникальный автоматически в базе...

2024-08-22 12:32 UTC, ArtemShendelyar commented
Благодарю за правки. С Flow и правда легче обстоят дела.

2024-08-22 13:04 UTC, Valentin2508247 requested changes

2024-08-22 13:04 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/home/HomeFragmentViewModel.kt
> +             portfolioInteractor.getPortfolioList().collect{
_assetsCount.value = portfolioItemInteractor.getPortfolioItemsList().count() не отработает

viewModelScope.launch запускает корутину
flow.collect прерывает корутину, возобновляя при получении элемента из flow и прерывая после обработки

до _assetsCount.value выполнение не доходит

2024-08-22 13:04 UTC, Valentin2508247 commented on app/build.gradle
> +    id 'androidx.navigation.safeargs.kotlin'
сделай плагины через alias и version catalogs

2024-08-22 13:04 UTC, Valentin2508247 commented on app/src/main/java/data/local/db/entity/PortfolioDb.kt
> +    val portfolio = Portfolio(id, name)
можно сразу return

2024-08-22 13:04 UTC, Valentin2508247 commented on app/src/main/java/data/datasource/interfaces/PortfolioDataSource.kt
> +import kotlinx.coroutines.flow.Flow
строку после импортов забыл

2024-08-22 13:04 UTC, Valentin2508247 commented on app/src/main/java/data/PortfolioDbDataSource.kt
> +        val portfolioDb = PortfolioDb(0, name)
не передавай id, он сам сгенерируется
только name

2024-08-22 13:04 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioDetailsViewModel.kt
> +            portfolioInteractor.getPortfolioById(id).collect {
возможно нежелательное поведение при collect flow из много раз вызываемых методов

каждый вызов fun fetchPortfolioById(id: Int) запускает корутину во viewModelScope
пока viewModel не уничтожится, viewModelScope не отменится и корутины в viewModelScope будут жить
Room будет отправлять данные во флоу, возобновляя множество корутин, выполняющих collect

2024-08-22 13:16 UTC, ArtemShendelyar commented on app/src/main/java/com/example/myassets/presentation/ui/home/HomeFragmentViewModel.kt
> +             portfolioInteractor.getPortfolioList().collect{
Надо переставить порядок. Угу.

2024-08-22 13:16 UTC, ArtemShendelyar commented on app/build.gradle
> +    id 'androidx.navigation.safeargs.kotlin'
В процессе другого ПРа.

2024-08-22 13:16 UTC, ArtemShendelyar commented on app/src/main/java/data/local/db/entity/PortfolioDb.kt
> +    val portfolio = Portfolio(id, name)
Сделаю

2024-08-22 14:12 UTC, ArtemShendelyar commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioDetailsViewModel.kt
> +            portfolioInteractor.getPortfolioById(id).collect {
Решил вернуть старую реализацию через обычный объект, а не Flow

2024-08-26 07:53 UTC, Valentin2508247 approved these changes

2024-08-26 09:14 UTC, merged