HomeFragment
ArtemShendelyar/MyAssets pull request #14
Opened 2024-08-19 11:05 UTC by belgoscode

# Изменения
- Создана верстка для HomeFragment.
- Реализована логика HomeFragment, подгружающая простую статистику при загрузке фрагмента. 
- Прописана локализация для его интерфейса.

![Screenshot_20240819_140347](https://github.com/user-attachments/assets/1b6bce4d-6616-47fa-9d8e-68519a39a479)

2024-08-19 11:08 UTC, ArtemShendelyar approved these changes
Красота!

2024-08-19 14:00 UTC, Valentin2508247 requested changes

2024-08-19 14:00 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/home/HomeFragment.kt
> +        viewModel.fetchStats()
почему viewModel.fetchStats() в onResume?
давай в onViewCreated

2024-08-19 14:00 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/home/HomeFragmentViewModel.kt
> +    init {
давай уберем init блок
тут дважды обращение к данным вызывается

2024-08-19 15:21 UTC, belgoscode commented on app/src/main/java/com/example/myassets/presentation/ui/home/HomeFragment.kt
> +        viewModel.fetchStats()
Для того, чтобы обновлять статистику в лайвдате вьюмодели на каждом переходе во вкладку (при возобновлении фрагмента). В ином случае эти цифры не меняются

2024-08-20 12:31 UTC, Valentin2508247 approved these changes

2024-08-20 12:31 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/home/HomeFragmentViewModel.kt
> +            _portfoliosCount.value = portfolioInteractor.getPortfolioList().count()
лучше запускать независимые запросы параллельно, а не последовательно

2024-08-20 13:18 UTC, belgoscode commented on app/src/main/java/com/example/myassets/presentation/ui/home/HomeFragmentViewModel.kt
> +            _portfoliosCount.value = portfolioInteractor.getPortfolioList().count()
учтем это в последующем

2024-08-20 13:18 UTC, merged