Базовая навигация
ArtemShendelyar/MyAssets pull request #5
Opened 2024-07-11 01:41 UTC by ArtemShendelyar

2024-07-11 10:34 UTC, ArtemShendelyar commented
![346345163-6b5fd8f2-0549-474e-bbcd-1c1cc845e9a0](https://github.com/ArtemShendelyar/MyAssets/assets/172491829/bee60667-e4ec-42f4-8fd6-75310553d5ec)

2024-07-11 11:08 UTC, belgoscode approved these changes

2024-07-11 13:16 UTC, Valentin2508247 requested changes

2024-07-11 13:16 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/assets/AssetListFragment.kt
> +        return inflater.inflate(R.layout.fragment_asset_list, container, false)
через binding

2024-07-11 13:16 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/ProtfolioListFragment.kt
> +        return inflater.inflate(R.layout.fragment_protfolio_list, container, false)
через binding

2024-07-11 13:16 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsFragment.kt
> +        return inflater.inflate(R.layout.fragment_settings, container, false)
аналогично

2024-07-11 13:16 UTC, Valentin2508247 commented on app/src/main/res/layout/activity_main.xml
> -        app:layout_constraintTop_toTopOf="parent" />
можно использовать Linear вместо ConstraintLauout

2024-07-11 13:16 UTC, Valentin2508247 commented on gradle/libs.versions.toml
> +preference = "1.2.0"
зачем нужны preference именно в этом pull request?

2024-07-11 14:20 UTC, ArtemShendelyar commented on gradle/libs.versions.toml
> +preference = "1.2.0"
Тыкал различные варианты навигации.

2024-07-11 16:19 UTC, ArtemShendelyar commented on app/src/main/res/layout/activity_main.xml
> -        app:layout_constraintTop_toTopOf="parent" />
Всё же подумал... Хочется оставить Consrtaint. Гибкую вёртску легче оптимизировать для разных экранов.

2024-07-11 16:59 UTC, ArtemShendelyar commented on app/src/main/res/layout/activity_main.xml
> -        app:layout_constraintTop_toTopOf="parent" />
Хотя, мне Паша показал веса у Linear... Всё, теперь круто!

2024-07-15 09:50 UTC, Valentin2508247 approved these changes

2024-07-15 10:22 UTC, merged