Доменные модели, архитектура данных
ArtemShendelyar/MyAssets pull request #6
Opened 2024-07-21 14:15 UTC by belgoscode

Работа со связанной с данными архитектурой приложения в слоях data и domain. Подключение хилта.

2024-07-21 15:08 UTC, RaShCat approved these changes
Гхм.

2024-07-21 15:59 UTC, ArtemShendelyar commented on app/src/main/java/domain/entity/Portfolio.kt
> +    val name: String
Пока не уверен насчёт этого... Но мне нужно подумать. Под нашу реализацию приложения как бы подходит.

2024-07-21 16:00 UTC, ArtemShendelyar approved these changes
Думаю, с этим можно работать...

2024-07-22 14:51 UTC, Valentin2508247 requested changes

2024-07-22 14:51 UTC, Valentin2508247 commented on app/src/main/java/domain/interactors/PortfolioInteractor.kt
> +    fun getPortfolioById(id: Int): Result<Portfolio> {
опционально:
можно сделать функцию расширения
inline fun <T, R> T.resultOf(block: T.() -> R): Result<R> {
    return try {
        Result.success(block())
    } catch (e: Exception) {
        Result.failure(e)
    }
}

тогда получится такой код:
fun getPortfolioById(id: Int): Result<Portfolio> {
    return resultOf {portfolioRepository.getPortfolioById(id)}
}

2024-07-22 14:51 UTC, Valentin2508247 commented on gradle/libs.versions.toml
> +hilt-compiler-v2461 = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
зачем отдельно hilt-compiler-v2461?

2024-07-22 14:51 UTC, Valentin2508247 commented on gradle/libs.versions.toml
> +hiltCompiler = "2.46.1"
почему разные версии?
2.51.1 и 2.46.1

2024-07-22 14:51 UTC, Valentin2508247 commented on gradle/libs.versions.toml
> +hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
в блок [plugins] в низу файла 
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }

2024-07-22 14:51 UTC, Valentin2508247 commented on build.gradle
> +    id 'com.google.dagger.hilt.android' version '2.46.1' apply false
не нужно дублировать версии в разных местах
alias(libs.plugins.hilt)

2024-07-23 15:25 UTC, Valentin2508247 approved these changes

2024-07-24 15:55 UTC, merged