Список портфелей (fragment + rv)
ArtemShendelyar/MyAssets pull request #7
Opened 2024-07-28 18:36 UTC by belgoscode

# Изменения
- Исправлены опечатки в названиях файлов.
- Создана верстка для фрагмента PortfolioList включающая RecyclerView, а так же верстка элементов этого rv.
- Реализована функциональность фрагмента PortfolioList, его вью-модель и RecyclerView с DiffUtil. 

Некоторые части фичи еще будут переписываться, так как они зависят от других. В некоторых местах прописан todo, выплевывающий соответствующий эксцепшн.

<img src="https://github.com/user-attachments/assets/5575812f-3d66-441d-a10b-33ac07afc744" height="700">

2024-07-29 04:37 UTC, ArtemShendelyar approved these changes

2024-07-29 08:52 UTC, Valentin2508247 requested changes

2024-07-29 08:52 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioListFragment.kt
> +        val rv = binding.portfolioListRv
локальная переменная не нужна
нет ничего плохого в обращении к binding

2024-07-29 08:52 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioListFragment.kt
> +        val adapter = viewModel.portfolioList.value?.let {
зачем nullable adapter?
если вдруг adapter окажется null, данные далее нигде не смогут обновиться
сделай как non nullable поле во фрагменте

2024-07-29 08:52 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioListFragment.kt
> +
лишняя строка

2024-07-29 08:52 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/rv/PortfolioListRvAdapter.kt
> +) : RecyclerView.Adapter<PortfolioListRvViewHolder>() {
давай использовать ListAdapter
это избавит от необходимости самому сохранять списки с данными и вызывать DiffUtil

2024-07-29 08:52 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/rv/PortfolioListRvAdapter.kt
> +    private val onClick: (Int) -> Unit
сделай интерфейс для обработки событий элементов и передавай инстанс интерфейса
в дальнейшем будет удобно расширять код и добавлять методы
например, такой:
interface PortfolioItemListener {
   fun onItemClick(itemId: Int)
}

2024-07-29 08:52 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_portfolio_list.xml
> +        android:text="My portfolios"
в ресурсы

2024-07-29 08:52 UTC, Valentin2508247 commented on app/src/main/res/layout/portfolio_rv_card.xml
> +            android:text="Select"
в ресурсы

2024-07-29 08:52 UTC, Valentin2508247 commented on app/src/main/res/layout/portfolio_rv_card.xml
> +    <RelativeLayout
точно ли нужен RelativeLayout?

2024-07-29 11:28 UTC, belgoscode commented on app/src/main/res/layout/fragment_portfolio_list.xml
> +        android:text="My portfolios"
Так и сделаем когда @ArtemShendelyar закончит фичу локализации, пока хардкодная заглушка.

2024-07-29 11:30 UTC, belgoscode commented on app/src/main/res/layout/portfolio_rv_card.xml
> +            android:text="Select"
Так же заглушка, в ожидании локализации от @ArtemShendelyar

2024-07-29 14:19 UTC, Valentin2508247 requested changes

2024-07-29 14:19 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioListFragment.kt
> +        val adapter = PortfolioListRvAdapter(viewModel.portfolioList.value!!)
передавать список в ListAdapter не нужно
еще !! может привести к крашу
передай реализацию интерфейса:
```
    val listener = object : PortfolioListItemListener {
        override fun onItemClick(itemId: Int) {
            TODO("Not yet implemented")
        }
        override fun onSelect(itemId: Int) {
            TODO("Not yet implemented")
        }
    }
```

2024-07-29 14:19 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/rv/PortfolioListRvAdapter.kt
> +    private var items: List<Portfolio>
в конструктор 
private val listener: PortfolioListItemListener

2024-07-29 14:19 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/rv/PortfolioListRvAdapter.kt
> +    private var items: List<Portfolio>
items в listAdapter не нужны

2024-07-29 14:19 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/rv/listeners/PortfolioListItemListenerImpl.kt
не нужен будет

2024-07-31 12:50 UTC, Valentin2508247 requested changes

2024-07-31 12:50 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/rv/PortfolioListRvAdapter.kt
> +    private var itemListener: PortfolioListItemListener
private val
создавай анонимный класс сразу в месте вызова конструктора
var делает flow приложения сложнее

2024-07-31 14:57 UTC, Valentin2508247 approved these changes

2024-07-31 16:12 UTC, merged