SettingsFragment + ButtomSheet
ArtemShendelyar/MyAssets pull request #8
Opened 2024-08-01 00:22 UTC by ArtemShendelyar

Опять баловался долго реализациями различными. 
Но как поменять язык приложению пока не допёр.
Андроид как бы и сам меняет локализацию, но хотелось бы через настройки что-ли.

А ещё я сомневаюсь, что ButtomSheet вообще хороший инструмент для реализации того функционала, что представлен в этом ПРе.

![studio64_U4MW7umG3N](https://github.com/user-attachments/assets/27fca257-ff60-4020-ad8b-7016eb33e253)

2024-08-01 05:35 UTC, belgoscode commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +    val defaultCurrency: LiveData<String>
Почему `default` а не `current`?

2024-08-01 05:40 UTC, belgoscode commented on app/src/main/res/layout/fragment_settings.xml
> +            android:text="USD" />
Уверен, что стоит хардкодить?

2024-08-01 05:40 UTC, belgoscode commented on app/src/main/res/layout/fragment_settings.xml
> +            android:text="Русский" />
И тут тоже уверен в хардкоде?

2024-08-01 11:00 UTC, ArtemShendelyar commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +    val defaultCurrency: LiveData<String>
Я долго думал. И не смог определиться между двумя названиями.

2024-08-01 11:00 UTC, ArtemShendelyar commented on app/src/main/res/layout/fragment_settings.xml
> +            android:text="Русский" />
Не-а.

2024-08-01 11:00 UTC, ArtemShendelyar commented on app/src/main/res/layout/fragment_settings.xml
> +            android:text="USD" />
Ваще нет.

2024-08-01 11:30 UTC, ArtemShendelyar commented
Теперь вот так:

![изображение](https://github.com/user-attachments/assets/d64ba4b0-e3bb-4677-a859-564fc1e68394)

2024-08-01 11:32 UTC, belgoscode approved these changes

2024-08-01 13:11 UTC, Valentin2508247 commented
Можно через spinner выпадающий список реализовать
Ну или диалог со списком / боттомшит

2024-08-01 13:56 UTC, Valentin2508247 requested changes

2024-08-01 13:56 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/util/BasicBottomSheetFragment.kt
> +    override fun onDestroy() {
в onDestroyView

2024-08-01 13:56 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +            _currentCurrency.value = settingsInteractor.getGlobalCurrency() ?: "BYN"
давай default value на уровне data и без харкода

2024-08-01 13:56 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +            _currentLanguage.value = settingsInteractor.getAppLanguage() ?: "Russian"
аналогично

2024-08-01 13:56 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +        _currentCurrency.value = currency
плохой подход, можно нарушить Single Source of Truce
например, если по какой-то причине значение в storage не сохранится
давай сделаем flow, который будет обновлять значение в LiveData

2024-08-01 13:56 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +    fun saveAppLanguage(language: String) {
аналогично

2024-08-01 13:56 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +) : ViewModel() {
так более читаемо
```
private val _currentCurrency = MutableLiveData<String>()
val currentCurrency: LiveData<String>
    get() = _currentCurrency

private val _currentLanguage = MutableLiveData<String>()
val currentLanguage: LiveData<String>
    get() = _currentLanguage
```

2024-08-01 13:56 UTC, Valentin2508247 commented on app/src/main/java/data/preferences/DataStoreRepositoryImpl.kt
> +    private val context: Context
не контекст, а объект DataStore<Preferences> из DI

2024-08-01 13:56 UTC, Valentin2508247 commented on app/src/main/java/domain/interactors/SettingsInteractor.kt
> +        dataStoreRepository.putString("GlobalCurrency", currency)
давай хранить ключи для префов на уровне объекта для работы с preference

2024-08-01 13:56 UTC, Valentin2508247 commented on app/src/main/java/domain/entity/Locales.kt
> +    val names: HashMap<String, String> = hashMapOf(
давай в ресурсы

2024-08-01 13:56 UTC, Valentin2508247 commented on app/src/main/res/values/strings.xml
> +    <string name="currency">Валюта</string>
почему перемешаны русские и английские стринги?
можно делать второй файл strings.xml, туда положить русские значения

2024-08-02 12:08 UTC, ArtemShendelyar commented on app/src/main/java/data/preferences/DataStoreRepositoryImpl.kt
> +    private val context: Context
У меня довольна иная реализация. Но попробуем иначе.

2024-08-05 05:26 UTC, ArtemShendelyar commented on app/src/main/java/com/example/myassets/presentation/util/BasicBottomSheetFragment.kt
> +    override fun onDestroy() {
Заменил.

2024-08-05 05:27 UTC, ArtemShendelyar commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +            _currentCurrency.value = settingsInteractor.getGlobalCurrency() ?: "BYN"
Угусь.

2024-08-07 14:00 UTC, ArtemShendelyar commented on app/src/main/res/values/strings.xml
> +    <string name="currency">Валюта</string>
Разбил на 2 файла. Оставил стандартную английскую локализацию.

2024-08-07 14:00 UTC, ArtemShendelyar commented on app/src/main/java/domain/entity/Locales.kt
> +    val names: HashMap<String, String> = hashMapOf(
Сунул как мог в ресурсы.

2024-08-07 14:01 UTC, ArtemShendelyar commented on app/src/main/java/domain/interactors/SettingsInteractor.kt
> +        dataStoreRepository.putString("GlobalCurrency", currency)
Сделал компаньоном в виде констант.

2024-08-08 00:02 UTC, pzinkevich42innowise requested changes

2024-08-08 00:02 UTC, pzinkevich42innowise commented on app/src/main/AndroidManifest.xml
> +        </service>
А это ещё к чему?

2024-08-08 00:02 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +            flowOf(currency).collect {
Зачем тут flow?

2024-08-08 00:02 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +            flowOf(languageStringUI).collect {
Зачем тут оборачивать во flow?

2024-08-08 00:02 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +            AppCompatDelegate.setApplicationLocales(appLocale)
Настройка языка приложения в современный версиях осуществляется прямо из системы. В остальных случаях мы должны следовать языку системы. И при любом раскладе нам обычно это реализовывать не требуется.

Не надо изобретать велосипед

2024-08-08 00:02 UTC, pzinkevich42innowise commented on app/src/main/java/data/preferences/DataStoreRepositoryImpl.kt
> +    override suspend fun putString(key: String, value: String) {
Кажется ты не так понял суть работы с простым хранилищем. Нельзя давать доступ извне к методам чтения и записи, поскольку это не типобезопасно. Должны быть методы работы с конкретным ключом:

putDefaultCurrency и getDefaultCurrency

2024-08-08 00:02 UTC, pzinkevich42innowise commented on app/src/main/java/data/preferences/DataStoreRepositoryImpl.kt
> +    override suspend fun clearPreference(key: String) {
С чего вдруг вообще извне data слоя кому-то управлять префами? Не задача ли это как раз репозитория? 

Твой Repository сейчас напоминает DataSource

2024-08-08 00:02 UTC, pzinkevich42innowise commented on app/src/main/java/domain/interactors/SettingsInteractor.kt
> +        private const val GLOBAL_CURRENCY_KEY = "GlobalCurrency"
Какую роль эти константы играют в бизнес-логике настроек?

2024-08-08 00:02 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_bottom_sheet_list.xml
> +<ListView xmlns:android="http://schemas.android.com/apk/res/android"
Слабо использовать актуальный Recycler, вместо устаревшего List?)

2024-08-08 07:01 UTC, ArtemShendelyar commented on app/src/main/AndroidManifest.xml
> +        </service>
Делал смену языка из приложения. По документации это поддержка Android 12<

2024-08-08 07:10 UTC, ArtemShendelyar commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +            AppCompatDelegate.setApplicationLocales(appLocale)
Зато я нашёл способ как это сделать!

2024-08-08 07:30 UTC, ArtemShendelyar commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +            flowOf(currency).collect {
Наверняка я не так понял Валентина.

2024-08-08 07:30 UTC, ArtemShendelyar commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsViewModel.kt
> +            flowOf(languageStringUI).collect {
Возможно я не так понял Валентина.

2024-08-08 07:32 UTC, ArtemShendelyar commented on app/src/main/java/domain/interactors/SettingsInteractor.kt
> +        private const val GLOBAL_CURRENCY_KEY = "GlobalCurrency"
Да я, оказывается, запутался в репозитории, интеракторе и т. п.
Сейчас сижу, исправляю.

2024-08-08 07:32 UTC, ArtemShendelyar commented on app/src/main/res/layout/fragment_bottom_sheet_list.xml
> +<ListView xmlns:android="http://schemas.android.com/apk/res/android"
Да нет. Сейчас исправлю...

2024-08-08 13:48 UTC, ArtemShendelyar commented on app/src/main/res/layout/fragment_bottom_sheet_list.xml
> +<ListView xmlns:android="http://schemas.android.com/apk/res/android"
Исправил.

2024-08-09 08:23 UTC, Valentin2508247 requested changes

2024-08-09 08:23 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/util/BasicBottomSheetFragment.kt
> +abstract class BasicBottomSheetFragment<VB : ViewBinding> : BottomSheetDialogFragment() {
может, я что-то упустил
где класс используется?

2024-08-09 08:23 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsFragment.kt
> +        private const val KEY_CURRENCY = "currencyKey"
используй ключи из CurrencyBottomSheetFragment

2024-08-09 08:23 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/settings/stringselector/CurrencyBottomSheetFragment.kt
> +    companion object {
используешь разные ключи для отправки и получения fragment result
сделай public и используй общие ключи

2024-08-09 10:19 UTC, ArtemShendelyar commented on app/src/main/java/com/example/myassets/presentation/ui/settings/stringselector/CurrencyBottomSheetFragment.kt
> +    companion object {
![изображение](https://github.com/user-attachments/assets/3af5148d-751d-4bbb-b8a7-75b62495a978)

2024-08-09 10:30 UTC, ArtemShendelyar commented on app/src/main/java/com/example/myassets/presentation/ui/settings/SettingsFragment.kt
> +        private const val KEY_CURRENCY = "currencyKey"
Okay.

2024-08-09 11:08 UTC, Valentin2508247 approved these changes

2024-08-09 11:22 UTC, merged