Couroutines & CRUD
ArtemShendelyar/MyAssets pull request #9
Opened 2024-08-06 16:02 UTC by belgoscode

# Изменения
- Перевел всю IO-инфраструктуру на корутины.
- Допилил оставленные CRUD фичи, пока что работающие со списком.
- Добавил кнопку "+" в PortfolioListFragment, создающую новый портфель.

p.s Я знаю, что `notifyDataSetChanged()` неоптимален, но другого решения, кроме как пинать ссылку на адаптер по всей инфраструктуре аж до самого data-слоя я не нашел, а это, как мне показалось, еще хуже.

2024-08-06 16:14 UTC, ArtemShendelyar approved these changes
Не нашёл ничего к чем придраться...

2024-08-07 08:10 UTC, Valentin2508247 requested changes

2024-08-07 08:10 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioListFragment.kt
> +            adapter.notifyDataSetChanged()
adapter.notifyDataSetChanged() не нужен
обновление списка в observe liveData

2024-08-07 08:10 UTC, Valentin2508247 commented on app/src/main/java/domain/interactors/PortfolioInteractor.kt
>          return resultOf {
поменяй resultOf на
```
inline fun <T, R> T.resultOf(block: T.() -> R): Result<R> {
    return try {
        Result.success(block())
    } 
    catch (e: CancellationException) {
        throw e
    }
    catch (e: Exception) {
            Result.failure(e)
    }
}
```

2024-08-07 08:10 UTC, Valentin2508247 commented on gradle/libs.versions.toml
> +javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }
зачем зависимость?

2024-08-07 11:28 UTC, Valentin2508247 requested changes

2024-08-07 11:28 UTC, Valentin2508247 commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioListViewModel.kt
> +    val _portfolioList = MutableLiveData<List<Portfolio>>()
оставь private

2024-08-07 11:30 UTC, belgoscode commented on app/src/main/java/com/example/myassets/presentation/ui/portfolios/PortfolioListViewModel.kt
> +    val _portfolioList = MutableLiveData<List<Portfolio>>()
Ой. Это я случайно налепил когда дебажил

2024-08-07 11:33 UTC, Valentin2508247 approved these changes

2024-08-07 11:34 UTC, merged